export const config = [
  { source: 'this', target: 'bind' },
  { source: 'this', target: 'apply' },
  { source: 'this', target: 'call' },
  { source: 'bind', target: 'new' },
  { source: 'new', target: 'this' },
  ['Object', 'Object.create'],
  ['Object', 'prototype'],
  ['prototype', 'bianli'],
  { source: 'new', target: 'Object.create' },
  { source: 'Object.create', target: 'prototype' },
  { source: 'Object.create', target: '__proto__' },
  { source: 'prototype', target: 'extend' },
  { source: 'extend', target: 'Class' },
  { source: 'Class', target: 'constructor' },
  { source: 'Class', target: 'Class-static' },
  { source: 'http', target: 'cookies' },
  { source: 'http', target: 'token' },
  { source: 'http', target: 'token' },
  { source: 'storage', target: 'cookies' },
  { source: 'storage', target: 'localStorage' },
  { source: 'storage', target: 'sessionStorage' },
  ['webpack', 'loader'],
  ['loader', 'asset-module'],
  ['webpack', 'plugins'],
  ['http', ['axios', 'fetch', 'jsonp', 'ajax']],
  ['axios', ['interceptor', 'fetch', 'jsonp', 'ajax']],
  [
    'Proxy',
    ['get', 'has', 'set', 'setPrototypeOf', 'getPrototypeOf', 'ownKeys', 'defineProperty', 'getOwnPropertyDecriptor', 'isExtensible', 'preventExtentions', 'deleteProperty', 'apply', 'constructor'],
  ],
  ['es6', 'Proxy'],
  ['es6', 'Reflect'],
]
