'use client'

import './globals.scss'
import type { Metadata } from 'next'
import { useEffect } from 'react'
import NavBar from '../components/NavBar'
import { getUrl } from '@/utils'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    console.log('window:', window)
  }, [])
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div>{children}</div>
      </body>
    </html>
  )
}
