'use client'

import './globals.scss'
import type { Metadata } from 'next'
import { useEffect } from 'react'
import { bus, setupApp, preloadApp, startApp, destroyApp } from 'wujie'
import NavBar from '../components/NavBar'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  if (typeof window !== undefined) {
  }

  return (
    <html lang="en">
      <body>
        <NavBar />
        <div>{children}</div>
      </body>
    </html>
  )
}
