'use client'

import './globals.css'
import type { Metadata } from 'next'
import { useEffect } from 'react'
import { bus, setupApp, preloadApp, startApp, destroyApp } from 'wujie'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  if (typeof window !== undefined) {
  }

  return (
    <html lang="en">
      <body>
        <div className="h-12 color-primary">HEAder</div>
        <div className="h-[800px]">{children}</div>
      </body>
    </html>
  )
}
