/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentBox: typeof import('./src/components/ContentBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    Iphone: typeof import('./src/components/iphone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
