// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Formlist: typeof import('./src/components/formlist/formlist.vue')['default']
    Pagination: typeof import('./src/components/pagination/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/swiper/swiper.vue')['default']
    TableEnhance: typeof import('./src/components/table-enhance/table-enhance.vue')['default']
  }
}
